export const JOBS = [
  { id: '11', jobId: 11, label: 'Chief Executive Officer', description: 'CHIEF EXECUTIVE OFFICER' },
  { id: '12', jobId: 12, label: 'Dy. GM (HR, Admin & Procurement)', description: 'DY. GM (HR, ADMIN & PROCUREMENT)' },
  { id: '13', jobId: 13, label: 'Manager Operations', description: 'MANAGER  OPERATIONS' },
  { id: '14', jobId: 14, label: 'Manager - Revenue & Billing', description: 'MANAGER - REVENUE & BILLING' },
  { id: '15', jobId: 15, label: 'Manager Media & Communication', description: 'MANAGER  MEDIA & COMMUNCATION' },
  { id: '16', jobId: 16, label: 'Sr. System Analyst', description: 'SR. SYSTEM ANALYST' },
  { id: '17', jobId: 17, label: 'AM - Solid Waste', description: 'AM - SOLID WASTE' },
  { id: '18', jobId: 18, label: 'AM - Water Supply', description: 'AM - WATER SUPPLY' },
  { id: '19', jobId: 19, label: 'AM - Media & Communication', description: 'AM - MEDIA & COMMUNICATION' },
  { id: '20', jobId: 20, label: 'AM - Procurement', description: 'AM - PROCUREMENT' },
  { id: '21', jobId: 21, label: 'AM - Human Resource', description: 'AM - HUMAN RESOURCE' },
  { id: '22', jobId: 22, label: 'AM - Accounts', description: 'AM - ACCOUNTS' },
  { id: '23', jobId: 23, label: 'Chief Financial Officer', description: 'CHIEF FINANCIAL OFFICER' },
  { id: '24', jobId: 24, label: 'Finance Specialist', description: 'FINANCE SPECIALIST' },
  { id: '25', jobId: 25, label: 'Fleet Officer', description: 'FLEET OFFICER' },
  { id: '26', jobId: 26, label: 'GIS Officer', description: 'GIS OFFICER' },
  { id: '27', jobId: 27, label: 'Sanitary Worker', description: 'SANITARY WORKER' },
  { id: '28', jobId: 28, label: 'TW Operator', description: 'TW OPERATOR' },
  { id: '29', jobId: 29, label: 'Computer Operator', description: 'COMPUTER OPERATOR' },
  { id: '30', jobId: 30, label: 'PS to CEO', description: 'PS TO CEO' },
  { id: '31', jobId: 31, label: 'Receptionist', description: 'RECEPTIONIST' },
  { id: '32', jobId: 32, label: 'Telephone Operator', description: 'TELEPHONE OPERATOR' },
  { id: '33', jobId: 33, label: 'Line Inspector', description: 'LINE INSPECTOR' },
  { id: '34', jobId: 34, label: 'Clerk', description: 'CLERK' },
  { id: '35', jobId: 35, label: 'Sr. Clerk', description: 'SR. CLERK' },
  { id: '36', jobId: 36, label: 'Peon/Massenger', description: 'PEON/MASSENGER' },
  { id: '37', jobId: 37, label: 'Sanitary Supervisor', description: 'SANITARY SUPERVISOR' },
  { id: '38', jobId: 38, label: 'Sanitary Inspector', description: 'SANITARY INSPECTOR' },
  { id: '39', jobId: 39, label: 'Driver', description: 'DRIVER' },
  { id: '40', jobId: 40, label: 'Sanitary Conductor', description: 'SANITARY CONDUCTOR' },
  { id: '41', jobId: 41, label: 'Sanitary Driver', description: 'SANITARY DRIVER' },
  { id: '42', jobId: 42, label: 'Office Boy', description: 'OFFICE BOY' },
  { id: '43', jobId: 43, label: 'Water Supply Specialist', description: 'WATER SUPPLY SPECIALIST' },
  { id: '44', jobId: 44, label: 'Accounts Officer', description: 'ACCOUNTS OFFICER' },
  { id: '45', jobId: 45, label: 'Cook', description: 'COOK' },
  { id: '46', jobId: 46, label: 'Admin and Procurement Officer', description: 'ADMIN AND PROCUREMENT OFFICER' },
  { id: '47', jobId: 47, label: 'Welder', description: 'WELDER' },
  { id: '48', jobId: 48, label: 'Security Guard', description: 'SECURITY GUARD' },
  { id: '49', jobId: 49, label: 'Accounts Assistant', description: 'ACCOUNTS ASSISTANT' },
  { id: '50', jobId: 50, label: 'Driver to CEO', description: 'DRIVER TO CEO' },
  { id: '51', jobId: 51, label: 'Vehicle Incharge', description: 'VEHICLE INCHARGE' },
  { id: '52', jobId: 52, label: 'Camera Man', description: 'CAMERA MAN' },
  { id: '53', jobId: 53, label: 'Watchman', description: 'WATCHMAN' },
  { id: '54', jobId: 54, label: 'Fleet Cum Mechanical Officer', description: 'FLEET CUM MECHANICAL OFFICER' },
  { id: '55', jobId: 55, label: 'Billing Officer', description: 'BILLING OFFICER' },
  { id: '56', jobId: 56, label: 'Intern - Civil Engineer', description: 'INTERN - CIVIL ENGINEER' },
  { id: '57', jobId: 57, label: 'AM - Water Supply & WWM', description: 'AM - WATER SUPPLY & WWM' },
  { id: '58', jobId: 58, label: 'Accounts Junior', description: 'ACCOUNTS JUNIOR' },
  { id: '59', jobId: 59, label: 'Associate Engineer', description: 'ASSOCIATE ENGINEER' },
  { id: '60', jobId: 60, label: 'Junior Clerk', description: 'JUNIOR CLERK' },
  { id: '61', jobId: 61, label: 'Draftsman', description: 'DRAFTSMAN' },
  { id: '62', jobId: 62, label: 'Naib Qasid', description: 'NAIB QASID' },
  { id: '63', jobId: 63, label: 'Pipe Fitter', description: 'PIPE FITTER' },
  { id: '64', jobId: 64, label: 'Line Man', description: 'LINE MAN' },
  { id: '65', jobId: 65, label: 'Valve Man', description: 'VALVE MAN' },
  { id: '66', jobId: 66, label: 'Quantity Surveyor', description: 'QUANTITY SURVEYOR' },
  { id: '67', jobId: 67, label: 'Sanitary Driver', description: 'SANITARY DRIVER' },
  { id: '68', jobId: 68, label: 'IT Assistant', description: 'IT ASSISTANT' },
  { id: '69', jobId: 69, label: 'Intern - Associate Engineer', description: 'INTERN - ASSOCIATE ENGINEER' },
  { id: '70', jobId: 70, label: 'Legal Advisor', description: 'LEGAL ADVISOR' },
  { id: '71', jobId: 71, label: 'Letigation Clerk', description: 'LETIGATION CLERK' },
  { id: '72', jobId: 72, label: 'MSW Sorting Specialist', description: 'MSW SORTING SPECIALIST' },
  { id: '73', jobId: 73, label: 'Managment Trainee Officer', description: 'MANAGMENT TRAINEE OFFICER' },
  { id: '74', jobId: 74, label: 'Stream Inspector', description: 'STREAM INSPECTOR' },
  { id: '75', jobId: 75, label: 'Stream Worker', description: 'STREAM WORKER' },
  { id: '76', jobId: 76, label: 'Assist to Manager Ops', description: 'ASSIST TO MANAGER OPS' },
  { id: '77', jobId: 77, label: 'Office Assistant', description: 'OFFICE ASSISTANT' },
  { id: '78', jobId: 78, label: 'Helper to Pipe Fitter', description: 'HELPER TO PIPE FITTER' },
  { id: '79', jobId: 79, label: 'Chief Sanitary Inspector', description: 'CHIEF SANITARY INSPECTOR' },
  { id: '80', jobId: 80, label: 'Asstt : Sanitary Inspector', description: 'ASSTT : SANITARY INSPECTOR' },
  { id: '81', jobId: 81, label: 'Blacksmith', description: 'BLACKSMITH' },
  { id: '82', jobId: 82, label: 'COVID19 Worker', description: 'COVID19 WORKER' },
  { id: '83', jobId: 83, label: 'Malaria Inspector', description: 'MALARIA INSPECTOR' },
  { id: '84', jobId: 84, label: 'Malaria Supervisor', description: 'MALARIA SUPERVISOR' },
  { id: '85', jobId: 85, label: 'Motor Transport Officer', description: 'MOTOR TRANSPORT OFFICER' },
  { id: '86', jobId: 86, label: 'Water Rate Collector', description: 'WATER RATE COLLECTOR' },
  { id: '87', jobId: 87, label: 'Dy.Manager - Solid Waste', description: 'DY.MANAGER - SOLID WASTE' },
  { id: '88', jobId: 88, label: 'Dy. Manager - Admin & Procurement', description: 'DY. MANAGER - ADMIN & PROCUREMENT' },
  { id: '89', jobId: 89, label: 'Billing Supervisor', description: 'BILLING SUPERVISOR' },
  { id: '90', jobId: 90, label: 'Technical Expert Network & Systems', description: 'TECHNICAL EXPERT NETWORK & SYSTEMS' },
  { id: '91', jobId: 91, label: 'Field Inspector Complaints', description: 'FIELD INSPECTOR COMPLAINTS' },
  { id: '92', jobId: 92, label: 'Helper', description: 'HELPER' },
  { id: '93', jobId: 93, label: 'GM (HR, Admin & Procurement)', description: 'GM (HR, ADMIN & PROCUREMENT)' },
  { id: '94', jobId: 94, label: 'Mechanical Officer', description: 'MECHANICAL OFFICER' },
  { id: '95', jobId: 95, label: 'Complaint Management Officer', description: 'COMPLAINT MANAGEMENT OFFICER' },
  { id: '96', jobId: 96, label: 'Senior Manager Commercial', description: 'SENIOR MANAGER COMMERCIAL' },
  { id: '97', jobId: 97, label: 'Admin Assistant', description: 'ADMIN ASSISTANT' },
  { id: '98', jobId: 98, label: 'Data Entry Assistant', description: 'DATA ENTRY ASSISTANT' },
  { id: '99', jobId: 99, label: 'Dy. Manager Accounts', description: 'DY. MANAGER ACCOUNTS' },
  { id: '100', jobId: 100, label: 'BCC Supervisor', description: 'BCC SUPERVISOR' },
  { id: '101', jobId: 101, label: 'BCC Coordinator', description: 'BCC COORDINATOR' },
  { id: '102', jobId: 102, label: 'AM - Finance', description: 'AM - FINANCE' },
  { id: '103', jobId: 103, label: 'Intern - Electrical Engineer', description: 'INTERN - ELECTRICAL ENGINEER' },
  { id: '104', jobId: 104, label: 'Manager Water Supply', description: 'MANAGER WATER SUPPLY' },
  { id: '105', jobId: 105, label: 'Manager Solid Waste', description: 'MANAGER SOLID WASTE' },
  { id: '106', jobId: 106, label: 'Manager Water Supply Operations', description: 'MANAGER WATER SUPPLY OPERATIONS' },
  { id: '107', jobId: 107, label: 'Media Officer', description: 'MEDIA OFFICER' },
  { id: '108', jobId: 108, label: 'Asst. Manager Human Resource', description: 'ASST. MANAGER HUMAN RESOURCE' },
  { id: '109', jobId: 109, label: 'Water Supply Inspector', description: 'WATER SUPPLY INSPECTOR' },
  { id: '110', jobId: 110, label: 'Billing Boy', description: 'BILLING BOY' },
  { id: '111', jobId: 111, label: 'Intern - Media Communication', description: 'INTERN - MEDIA COMMUNICATION' },
  { id: '112', jobId: 112, label: 'Excavator Operator', description: 'EXCAVATOR OPERATOR' },
  { id: '113', jobId: 113, label: 'Payroll Officer', description: 'PAYROLL OFFICER' },
  { id: '114', jobId: 114, label: 'Valve Woman', description: 'VALVE WOMAN' },
  { id: '115', jobId: 115, label: 'GM Operations & Engineering Services', description: 'GM OPERATIONS & ENGINEERING SERVICES' },
  { id: '117', jobId: 117, label: 'Internee', description: 'INTERNEE' },
  { id: '118', jobId: 118, label: 'Legal Assistant', description: 'LEGAL ASSISTANT' },
  { id: '119', jobId: 119, label: 'Internal Auditor', description: 'INTERNAL AUDITOR' },
  { id: '120', jobId: 120, label: 'Office Cum File Assistant', description: 'OFFICE CUM FILE ASSISTANT' },
  { id: '121', jobId: 121, label: 'Repair & Maintenance Incharge', description: 'REPAIR & MAINTENANCE INCHARGE' },
  { id: '122', jobId: 122, label: 'Admin Officer', description: 'ADMIN OFFICER' },
  { id: '123', jobId: 123, label: 'HR Officer', description: 'HR OFFICER' },
  { id: '124', jobId: 124, label: 'Billing Assistant', description: 'BILLING ASSISTANT' },
  { id: '125', jobId: 125, label: 'Assist to GM Ops & Engr. Services', description: 'ASSIST TO GM OPS & ENGR. SERVICES' },
];

export const getJobLabel = (jobId) => {
  if (!jobId) {
    return 'Unassigned';
  }
  const job = JOBS.find((item) => item.id === String(jobId) || item.jobId === parseInt(jobId));
  return job ? job.label : `Job ${jobId}`;
};

export const getJobById = (jobId) => {
  if (!jobId) return null;
  const numericId = typeof jobId === 'string' ? parseInt(jobId) : jobId;
  return JOBS.find((job) => job.jobId === numericId || job.id === String(jobId));
};

export const getJobByDescription = (description) => {
  if (!description) return null;
  return JOBS.find((job) => 
    job.description.toUpperCase() === description.toUpperCase() ||
    job.label.toUpperCase() === description.toUpperCase()
  );
};
